---
sidebar: sidebar 
permalink: vsphere-kubernetes-service/vks-overview.html 
keywords: vks, vSphere Kubernetes Service, ONTAP, kubernetes, overview 
summary: vSphere Kubernetes Service と、それが NetApp ONTAP とコンテナ化されたワークロード向けにどのように統合されるかについて説明します。 
---
= vSphere Kubernetes Service と NetApp ONTAP について学ぶ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
vSphere Kubernetes Service（VKS）は、VMwareが提供するマネージドKubernetesサービスであり、組織がKubernetesを使用してコンテナ化されたアプリケーションをデプロイ、管理、拡張することを可能にします。NetApp ONTAPストレージと組み合わせることで、VKSはクラウドネイティブワークロードにエンタープライズクラスの永続性、パフォーマンス、およびデータ管理を提供します。

vSphere Kubernetes Service は通常、VMware Tanzu などの VMware のより広範なエコシステムに統合されており、Kubernetes 管理、アプリケーションの最新化、および DevOps プラクティスのための包括的なツールスイートを提供します。



[[key-features-of-vsphere-kubernetes-service]]
== vSphere Kubernetes Serviceの主な機能

. *マネージドKubernetesクラスター:* vSphere Kubernetes Serviceは、Kubernetesクラスターのデプロイと管理を簡素化します。クラスターの作成、アップグレード、スケーリング、監視といったタスクを自動化します。
. *VMware インフラストラクチャとの統合：* VKS は VMware vSphere、NSX-T、およびその他の VMware ソリューションとシームレスに統合し、組織が既存の VMware インフラストラクチャを Kubernetes ワークロードに活用できるようにします。
. *マルチクラウドおよびハイブリッドクラウドのサポート：* vSphere Kubernetes Serviceは、プライベートクラウド、パブリッククラウド（AWS、Azure、Google Cloudなど）、およびハイブリッドクラウド環境へのデプロイをサポートしており、組織がアプリケーションを管理する上での柔軟性を提供します。
. *組み込みセキュリティ：* VKSには、ロールベースのアクセス制御（RBAC）、ポリシー適用、およびネットワークセキュリティのためのVMware NSXとの統合などのセキュリティ機能が含まれています。
. *開発者向けツール：* vSphere Kubernetes Serviceは、Tanzu Application Platformなどの開発者ツールと統合することで、コンテナ化されたアプリケーションの開発とデプロイを簡素化します。
. *拡張性と高可用性：* VKSは、アプリケーションの高い可用性とパフォーマンスを維持するために、自動スケーリングやフォールトトレランスなどの機能を提供します。
. *可観測性と監視：* vSphere Kubernetes Service は VMware Tanzu Observability （旧 Wavefront） およびその他の監視ツールと統合し、クラスターおよびアプリケーションのパフォーマンスに関するリアルタイムの洞察を提供します。
. *Kubernetesエコシステムのサポート：* VKSはアップストリームのKubernetesに完全に準拠しており、Kubernetes APIをサポートし、Helm、Istio、PrometheusなどのKubernetesネイティブツールと連携します。




[[use-cases-for-vsphere-kubernetes-service]]
== vSphere Kubernetes Serviceのユースケース

. *アプリケーションの最新化：* 組織は、レガシーアプリケーションをコンテナ化し、VKS によって管理される Kubernetes クラスターにデプロイすることで、レガシーアプリケーションを最新化できます。
. *DevOps Enablement:* VKS は、自動化、CI/CD 統合、開発者向けツールを提供することで、DevOps ワークフローをサポートします。
. *ハイブリッドクラウド展開：* 企業はVKSを使用して、オンプレミスとクラウド環境にまたがるKubernetesクラスターを展開し、一貫した運用を実現できます。
. *マイクロサービスアーキテクチャ：* VKSはマイクロサービスベースのアプリケーション開発をサポートしており、チームが分散システムを構築および拡張できます。

