---
sidebar: sidebar 
permalink: tanzu/vtwn-solution-overview.html 
keywords: VMware Tanzu, Tanzu, DevOps, Netapp, Trident, Trident Protect 
summary: 'このリファレンス ドキュメントでは、NetApp によって検証された複数の異なるデータ センター環境に Tanzu Kubernetes Grid (TKG)、Tanzu Kubernetes Grid Service (TKGS)、または Tanzu Kubernetes Grid Integrated (TKGI) として導入された、さまざまなNetApp Tanzu Kubernetes ソリューションの導入検証について説明します。' 
---
= NVA-1166: VMware Tanzu とNetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


アラン・カウルズとニヒル・M・クルカルニ（NetApp）

[role="lead"]
このリファレンス ドキュメントでは、NetApp によって検証された複数の異なるデータ センター環境に Tanzu Kubernetes Grid (TKG)、Tanzu Kubernetes Grid Service (TKGS)、または Tanzu Kubernetes Grid Integrated (TKGI) として導入された、さまざまなNetApp Tanzu Kubernetes ソリューションの導入検証について説明します。また、永続ストレージの管理のためのNetAppストレージ システムおよびTridentストレージ オーケストレータとのストレージ統合、およびその永続ストレージを使用するステートフル アプリケーションのバックアップとクローン作成のためのTrident Protect についても説明します。最後に、このドキュメントでは、ソリューションの統合と検証のビデオ デモを提供します。



== ユースケース

VMware Tanzu with NetAppソリューションは、次のようなユースケースを持つ顧客に卓越した価値を提供するように設計されています。

* VMware vSphere 上に展開され、 NetAppストレージ システムと統合された VMware Tanzu Kubernetes Grid オファリングを簡単に展開および管理できます。
* エンタープライズ コンテナと仮想化ワークロードを VMware Tanzu Kubernetes Grid 製品と組み合わせたパワー。
* NetAppストレージおよびNetApp Trident製品スイートと組み合わせて使用した場合の VMware Tanzu の機能を強調した実際の構成と使用例。
* Trident Protect を使用して、 NetAppストレージ システムにデータが存在する VMware Tanzu Kubernetes Grid クラスタに展開されたコンテナ化されたワークロードのアプリケーション整合性のある保護または移行。




== ビジネス価値

企業は、新製品の作成、リリース サイクルの短縮、新機能の迅速な追加のために DevOps プラクティスを採用するケースが増えています。コンテナとマイクロサービスは、その本質的なアジャイル性により、DevOps プラクティスのサポートにおいて重要な役割を果たします。ただし、エンタープライズ環境の運用規模で DevOps を実践するには、独自の課題があり、基盤となるインフラストラクチャに次のような特定の要件が課せられます。

* スタック内のすべてのレイヤーで高可用性を実現
* 導入手順の容易さ
* 中断のない運用とアップグレード
* マイクロサービスの俊敏性を維持するための API 駆動型でプログラム可能なインフラストラクチャ
* パフォーマンス保証付きのマルチテナンシー
* 仮想化されたワークロードとコンテナ化されたワークロードを同時に実行する機能
* ワークロードの需要に応じてインフラストラクチャを個別に拡張できる機能
* オンプレミスのデータセンターとクラウドの両方でコンテナを実行するハイブリッド クラウド モデルで展開する機能。


VMware Tanzu with NetApp はこれらの課題を認識し、顧客が選択したハイブリッド クラウド環境に VMware Tanzu Kubernetes サービスを導入することで、それぞれの懸念に対処するソリューションを提供します。



== 技術概要

VMware Tanzu with NetAppソリューションは、次の主要コンポーネントで構成されています。



=== VMware Tanzu Kubernetes プラットフォーム

VMware Tanzu にはさまざまなバージョンがあり、 NetAppのソリューション エンジニアリング チームがラボで検証しています。 Tanzu の各リリースはNetAppストレージ ポートフォリオと正常に統合され、それぞれが特定のインフラストラクチャの要求を満たすのに役立ちます。次の箇条書きのハイライトでは、このドキュメントで説明されている Tanzu の各バージョンの機能と提供内容について説明します。

*VMware Tanzu Kubernetes グリッド (TKG)*

* VMware vSphere 環境にデプロイされた標準的なアップストリーム Kubernetes 環境。
* 以前は Essential PKS として知られていました (2019 年 2 月の Heptio 買収により)。
* TKG は、vSphere 6.7U3 以降のサポートのために、個別の管理クラスタ インスタンスとともに展開されます。
* TKG デプロイメントは、AWS または Azure を使用してクラウドにもデプロイできます。
* Windows または Linux ワーカー ノード (Ubuntu/Photon) の使用を許可します。
* コントロール プレーンには、NSX-T、HA プロキシ、AVI ネットワーク、またはロード バランサを使用できます。
* TKG は、アプリケーション/データ プレーンに対して MetalLB をサポートします。
* vSphere CSI だけでなく、 NetApp Tridentなどのサードパーティ CSI も使用できます。


*VMware Tanzu Kubernetes グリッド サービス (TKGS)*

* VMware vSphere 環境にデプロイされた標準的なアップストリーム Kubernetes 環境。
* 以前は Essential PKS として知られていました (2019 年 2 月の Heptio 買収により)。
* TKGS は、vSphere 7.0U1 以降でのみ、スーパーバイザー クラスタおよびワークロード クラスタと共にデプロイされます。
* Windows または Linux ワーカー ノード (Ubuntu/Photon) の使用を許可します。
* コントロール プレーンには、NSX-T、HA プロキシ、AVI ネットワーク、またはロード バランサを使用できます。
* TKGS は、アプリケーション/データ プレーンに対して MetalLB をサポートします。
* vSphere CSI だけでなく、 NetApp Tridentなどのサードパーティ CSI も使用できます。
* Tanzu を使用した vSphere Pod のサポートを提供し、環境内の有効な ESXi ホスト上でポッドを直接実行できるようにします。


*VMWare Tanzu Kubernetes グリッド統合 (TKGI)*

* 以前は Enterprise PKS として知られていました (2019 年 2 月の Heptio 買収により)。
* NSX-T、HA Proxy、または Avi を使用できます。独自のロードバランサーを提供することもできます。
* vSphere 6.7U3 以降、AWS、Azure、GCP でサポートされます。
* ウィザードによるセットアップにより、簡単に導入できます。
* BOSH によって管理される制御された不変の VM で Tanzu を実行します。
* vSphere CSI だけでなく、 NetApp Tridentなどのサードパーティ CSI も使用できます (いくつかの条件が適用されます)。


*vSphere と Tanzu (vSphere Pods)*

* vSphere ネイティブ ポッドは、完全な分離のために規定された仮想ハードウェアを備えた薄い Photon ベースのレイヤーで実行されます。
* NSX-T が必要ですが、これにより Harbor イメージ レジストリなどの追加機能のサポートが可能になります。
* TKGS などの仮想スーパーバイザー クラスタを使用して vSphere 7.0U1 以降に展開および管理されます。  ESXi ノード上でポッドを直接実行します。
* vSphere が完全に統合されており、vSphere 管理による最高の可視性と制御を実現します。
* 最高レベルのセキュリティを実現する分離された CRX ベースのポッド。
* 永続ストレージには vSphere CSI のみをサポートします。サードパーティのストレージ オーケストレーターはサポートされていません。




=== NetApp ストレージ システム

NetApp には、エンタープライズ データ センターやハイブリッド クラウドの導入に最適なストレージ システムがいくつかあります。  NetAppポートフォリオには、 NetApp ONTAP、 NetApp Element、 NetApp e-Series ストレージ システムが含まれており、いずれもコンテナ化されたアプリケーションに永続的なストレージを提供できます。

詳細については、 NetAppのWebサイトをご覧ください。 https://www.netapp.com["ここをクリックしてください。"] 。



=== NetAppストレージ統合

Trident は、VMware Tanzu を含むコンテナおよび Kubernetes ディストリビューション向けのオープンソースで完全にサポートされているストレージ オーケストレーターです。

詳細については、Tridentのウェブサイトをご覧ください。 https://docs.netapp.com/us-en/trident/index.html["ここをクリックしてください。"] 。



== 検証済みリリースの現在のサポート マトリックス

|===


| テクノロジ | 目的 | ソフトウェア バージョン 


| NetApp ONTAP | ストレージ | 9.9.1 


| NetAppTrident | ストレージオーケストレーション | 22.04.0 


| VMware Tanzu Kubernetes グリッド | コンテナオーケストレーション | 1.4+ 


.2+| VMware Tanzu Kubernetes グリッド サービス .2+| コンテナオーケストレーション | 0.0.15 [vSphere 名前空間] 


| 1.22.6 [スーパーバイザークラスター Kubernetes] 


| VMware Tanzu Kubernetes Grid 統合 | コンテナオーケストレーション | 1.13.3 


| VMware vSphere | データセンター仮想化 | 7.0U3 


| VMware NSX-T データセンター | ネットワークとセキュリティ | 3.1.3 


| VMware NSX アドバンスド ロードバランサ | ロード バランサ | 20.1.3 
|===