---
sidebar: sidebar 
permalink: anthos/anthos-trident-ontap-nfs.html 
keywords: Trident, Trident, ONTAP, AFF, FAS, NFS 
summary: TridentとNetApp ONTAPストレージ システムとの統合を有効にするには、ストレージ システムとの通信を可能にするバックエンドを作成する必要があります。 
---
= NetApp ONTAP NFS構成
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
TridentとNetApp ONTAPストレージ システムとの統合を有効にするには、ストレージ システムとの通信を可能にするバックエンドを作成する必要があります。

. ダウンロードしたインストールアーカイブには、サンプルのバックエンドファイルが含まれています。 `sample-input`フォルダー階層。  NFSを提供するNetApp ONTAPシステムの場合は、 `backend-ontap-nas.json`ファイルを作業ディレクトリに移動し、編集します。
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/backends-samples/ontap-nas/backend-ontap-nas.json ./
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi backend-ontap-nas.json
----
. このファイル内の backendName、managementLIF、dataLIF、svm、username、および password の値を編集します。
+
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "backendName": "ontap-nas+10.61.181.221",
    "managementLIF": "172.21.224.201",
    "dataLIF": "10.61.181.221",
    "svm": "trident_svm",
    "username": "cluster-admin",
    "password": "password"
}
----
+

NOTE: 簡単に識別できるように、カスタム backendName 値を storageDriverName と NFS を提供している dataLIF の組み合わせとして定義するのがベスト プラクティスです。

. このバックエンド ファイルを配置したら、次のコマンドを実行して最初のバックエンドを作成します。
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ ./tridentctl -n trident create backend -f backend-ontap-nas.json
+-------------------------+----------------+--------------------------------------+--------+---------+
|          NAME           | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+-------------------------+----------------+--------------------------------------+--------+---------+
| ontap-nas+10.61.181.221 | ontap-nas      | be7a619d-c81d-445c-b80c-5c87a73c5b1e | online |       0 |
+-------------------------+----------------+--------------------------------------+--------+---------+
----
. バックエンドを作成したら、次にストレージ クラスを作成する必要があります。バックエンドと同様に、sample-inputs フォルダーには、環境に合わせて編集できるサンプル ストレージ クラス ファイルがあります。それを作業ディレクトリにコピーし、作成されたバックエンドを反映するために必要な編集を行います。
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/storage-class-samples/storage-class-csi.yaml.templ ./storage-class-basic.yaml
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi storage-class-basic.yaml
----
. このファイルで編集する必要があるのは、 `backendType`新しく作成されたバックエンドのストレージ ドライバーの名前に値を設定します。また、後の手順で参照する必要がある名前フィールドの値にも注意してください。
+
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-csi
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
----
+

NOTE: オプションフィールドがあります `fsType`このファイルで定義されます。この行は NFS バックエンドでは削除できます。

. 実行 `kubectl`ストレージ クラスを作成するコマンド。
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl create -f storage-class-basic.yaml
storageclass.storage.k8s.io/basic-csi created
----
. ストレージ クラスを作成したら、最初の永続ボリューム要求 (PVC) を作成する必要があります。サンプルがあります `pvc-basic.yaml`このアクションを実行するために使用できるファイルは、sample-inputs にもあります。
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/pvc-samples/pvc-basic.yaml ./
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi pvc-basic.yaml
----
. このファイルに対して行う必要がある唯一の編集は、 `storageClassName`フィールドは、先ほど作成したものと一致します。  PVC 定義は、プロビジョニングするワークロードの必要に応じてさらにカスタマイズできます。
+
[listing]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
. PVCを作成するには、 `kubectl`指示。作成するバックアップボリュームのサイズによっては、作成に時間がかかる場合があります。そのため、プロセスが完了するまで監視することができます。
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl create -f pvc-basic.yaml
persistentvolumeclaim/basic created

[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
basic   Bound    pvc-b4370d37-0fa4-4c17-bd86-94f96c94b42d   1Gi        RWO            basic-csi      7s
----

