---
sidebar: sidebar 
permalink: openshift/os-multitenancy-overview.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, Red Hat OpenShift, Multitenancy, Multi-tenancy 
summary: NetAppを使用した Red Hat OpenShift でのマルチテナントの構成 
---
= NetAppを使用したRed Hat OpenShiftでのマルチテナントの構成
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
コンテナ上で複数のアプリケーションやワークロードを実行する多くの組織では、アプリケーションまたはワークロードごとに 1 つの Red Hat OpenShift クラスターをデプロイする傾向があります。これにより、アプリケーションまたはワークロードの厳密な分離を実装し、パフォーマンスを最適化し、セキュリティの脆弱性を軽減することができます。ただし、アプリケーションごとに個別の Red Hat OpenShift クラスターを展開すると、独自の問題が発生します。各クラスターを個別に監視および管理する必要があるため運用オーバーヘッドが増加し、さまざまなアプリケーションに専用のリソースが割り当てられるためコストが増加し、効率的なスケーラビリティが妨げられます。

これらの問題を克服するには、すべてのアプリケーションまたはワークロードを単一の Red Hat OpenShift クラスターで実行することを検討できます。しかし、このようなアーキテクチャでは、リソースの分離とアプリケーションのセキュリティの脆弱性が大きな課題の 1 つとなります。あるワークロードのセキュリティ上の脆弱性は、当然のことながら別のワークロードに波及し、影響範囲が拡大する可能性があります。さらに、デフォルトではリソース割り当てポリシーがないため、あるアプリケーションによる突然の制御されていないリソース使用は、別のアプリケーションのパフォーマンスに影響を及ぼす可能性があります。

したがって、組織は、すべてのワークロードを単一のクラスターで実行しながらも、各ワークロード専用のクラスターの利点を提供するなど、両方の長所を取り入れたソリューションを求めています。

そのような効果的なソリューションの 1 つは、Red Hat OpenShift でマルチテナントを構成することです。マルチテナンシーとは、リソースやセキュリティなどを適切に分離しながら、複数のテナントが同じクラスター上で共存できるようにするアーキテクチャです。このコンテキストでは、テナントは、特定のユーザー グループが排他的な目的で使用するように構成されたクラスター リソースのサブセットとして見ることができます。  Red Hat OpenShift クラスターでマルチテナントを構成すると、次の利点が得られます。

* クラスタリソースの共有を可能にすることで、設備投資と運用コストを削減
* 運用および管理のオーバーヘッドの削減
* セキュリティ侵害の相互汚染からワークロードを保護する
* リソース競合による予期せぬパフォーマンス低下からワークロードを保護する


完全に実現されたマルチテナント OpenShift クラスターの場合、コンピューティング、ストレージ、ネットワーク、セキュリティなどのさまざまなリソース バケットに属するクラスター リソースに対してクォータと制限を構成する必要があります。このソリューションでは、すべてのリソース バケットの特定の側面を取り上げますが、NetApp ONTAP を基盤とするTridentによって動的に割り当てられるNetAppONTAPにマルチテナントを構成することで、同じ Red Hat OpenShift クラスター上の複数のワークロードによって提供または消費されるデータを分離して保護するためのベスト プラクティスに重点を置いています。
