---
sidebar: sidebar 
permalink: openshift/os-solution-overview.html 
keywords: NVA-1160, Red Hat, OpenShift, Netapp, Trident 
summary: 'このリファレンス ドキュメントでは、 NetAppによって検証された、インストーラー プロビジョニング インフラストラクチャ (IPI) を通じて複数の異なるデータセンター環境に導入された Red Hat OpenShift ソリューションの導入検証について説明します。また、永続ストレージの管理にTridentストレージ オーケストレーターを利用することで、 NetAppストレージ システムとのストレージ統合についても詳しく説明します。最後に、いくつかのソリューション検証と実際の使用例が調査され、文書化されます。' 
---
= NVA-1160: NetAppを使用した Red Hat OpenShift
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


アラン・カウルズとニヒル・M・クルカルニ（NetApp）

[role="lead"]
このリファレンス ドキュメントでは、 NetAppによって検証された、インストーラー プロビジョニング インフラストラクチャ (IPI) を通じて複数の異なるデータセンター環境に導入された Red Hat OpenShift ソリューションの導入検証について説明します。また、永続ストレージの管理にTridentストレージ オーケストレーターを利用することで、 NetAppストレージ システムとのストレージ統合についても詳しく説明します。最後に、いくつかのソリューション検証と実際の使用例が調査され、文書化されます。



== ユースケース

Red Hat OpenShift with NetAppソリューションは、次のようなユースケースを持つ顧客に卓越した価値を提供するように設計されています。

* ベアメタル、Red Hat OpenStack Platform、Red Hat Virtualization、VMware vSphere に IPI (Installer Provisioned Infrastructure) を使用してデプロイされた Red Hat OpenShift を簡単にデプロイおよび管理できます。
* エンタープライズ コンテナと仮想化ワークロードのパワーを、OSP、RHV、vSphere 上に仮想的にデプロイされた Red Hat OpenShift、または OpenShift Virtualization によるベアメタル上にデプロイされた Red Hat OpenShift と組み合わせます。
* NetAppストレージおよび Kubernetes 用のオープンソース ストレージ オーケストレーターであるTridentと組み合わせて使用した場合の Red Hat OpenShift の機能を強調した実際の構成と使用例。




== ビジネス価値

企業は、新製品の作成、リリース サイクルの短縮、新機能の迅速な追加のために DevOps プラクティスを採用するケースが増えています。コンテナとマイクロサービスは、その本質的なアジャイル性により、DevOps プラクティスのサポートにおいて重要な役割を果たします。ただし、エンタープライズ環境の運用規模で DevOps を実践するには、独自の課題があり、基盤となるインフラストラクチャに次のような特定の要件が課せられます。

* スタック内のすべてのレイヤーで高可用性を実現
* 導入手順の容易さ
* 中断のない運用とアップグレード
* マイクロサービスの俊敏性を維持するための API 駆動型でプログラム可能なインフラストラクチャ
* パフォーマンス保証付きのマルチテナンシー
* 仮想化されたワークロードとコンテナ化されたワークロードを同時に実行する機能
* ワークロードの需要に応じてインフラストラクチャを個別に拡張できる機能


NetAppを使用した Red Hat OpenShift はこれらの課題を認識し、顧客が選択したデータセンター環境で RedHat OpenShift IPI の完全自動導入を実装することにより、各懸念に対処するソリューションを提供します。



== 技術概要

Red Hat OpenShift with NetAppソリューションは、次の主要コンポーネントで構成されています。



=== Red Hat OpenShift コンテナ プラットフォーム

Red Hat OpenShift Container Platform は、完全にサポートされているエンタープライズ Kubernetes プラットフォームです。  Red Hat はオープンソースの Kubernetes にいくつかの機能強化を加え、コンテナ化されたアプリケーションを構築、展開、管理するためのすべてのコンポーネントが完全に統合されたアプリケーション プラットフォームを提供します。

詳細については、OpenShift の Web サイトをご覧ください。 https://www.openshift.com["ここをクリックしてください。"] 。



=== NetApp ストレージ システム

NetApp には、エンタープライズ データ センターやハイブリッド クラウドの導入に最適なストレージ システムがいくつかあります。  NetAppポートフォリオには、 NetApp ONTAP、 NetApp Element、 NetApp e-Series ストレージ システムが含まれており、いずれもコンテナ化されたアプリケーションに永続的なストレージを提供できます。

詳細については、 NetAppのWebサイトをご覧ください。 https://www.netapp.com["ここをクリックしてください。"] 。



=== NetAppストレージ統合

Trident は、Red Hat OpenShift を含むコンテナおよび Kubernetes ディストリビューション向けのオープンソースで完全にサポートされているストレージ オーケストレーターです。

詳細については、Tridentのウェブサイトをご覧ください。 https://docs.netapp.com/us-en/trident/index.html["ここをクリックしてください。"] 。



== 高度な設定オプション

このセクションでは、専用のプライベート イメージ レジストリの作成やカスタム ロード バランサ インスタンスのデプロイなど、このソリューションを本番環境にデプロイするときに実際のユーザーが実行する必要があるカスタマイズについて説明します。



== 検証済みリリースの現在のサポート マトリックス

|===


| テクノロジ | 目的 | ソフトウェア バージョン 


| NetApp ONTAP | ストレージ | 9.8、9.9.1、9.12.1 


| NetApp Element | ストレージ | 12.3 


| NetAppTrident | ストレージオーケストレーション | 22.01.0、23.04、23.07、23.10、24.02 


| レッドハット オープンシフト | コンテナオーケストレーション | 4.6 EUS、4.7、4.8、4.10、4.11、4.12、4.13、4.14 


| VMware vSphere | データセンター仮想化 | 7.0、8.0.2 
|===