---
sidebar: sidebar 
permalink: openshift/os-trident-element-iscsi.html 
summary:  
keywords: Trident, Element, Solidfire, iSCSI 
---
= NetApp Element iSCSI 構成
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
TridentとNetApp Elementストレージ システムとの統合を有効にするには、iSCSI プロトコルを使用してストレージ システムとの通信を可能にするバックエンドを作成する必要があります。

. ダウンロードしたインストールアーカイブには、サンプルのバックエンドファイルが含まれています。 `sample-input`フォルダー階層。  iSCSIを提供するNetApp Elementシステムの場合は、 `backend-solidfire.json`ファイルを作業ディレクトリに移動し、編集します。
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/backends-samples/solidfire/backend-solidfire.json ./
[netapp-user@rhel7 trident-installer]$ vi ./backend-solidfire.json
----
+
.. ユーザー、パスワード、MVIP値を編集します。 `EndPoint`ライン。
.. 編集する `SVIP`価値。
+
[listing]
----
 {
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://trident:password@172.21.224.150/json-rpc/8.0",
    "SVIP": "10.61.180.200:3260",
    "TenantName": "trident",
    "Types": [{"Type": "Bronze", "Qos": {"minIOPS": 1000, "maxIOPS": 2000, "burstIOPS": 4000}},
              {"Type": "Silver", "Qos": {"minIOPS": 4000, "maxIOPS": 6000, "burstIOPS": 8000}},
              {"Type": "Gold", "Qos": {"minIOPS": 6000, "maxIOPS": 8000, "burstIOPS": 10000}}]
}
----


. このバックエンド ファイルを配置したら、次のコマンドを実行して最初のバックエンドを作成します。
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ ./tridentctl -n trident create backend -f backend-solidfire.json
+-------------------------+----------------+--------------------------------------+--------+---------+
|          NAME           | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+-------------------------+----------------+--------------------------------------+--------+---------+
| solidfire_10.61.180.200 | solidfire-san  | b90783ee-e0c9-49af-8d26-3ea87ce2efdf | online |       0 |
+-------------------------+----------------+--------------------------------------+--------+---------+
----
. バックエンドを作成したら、次にストレージ クラスを作成する必要があります。バックエンドと同様に、sample-inputs フォルダーには、環境に合わせて編集できるサンプル ストレージ クラス ファイルがあります。それを作業ディレクトリにコピーし、作成されたバックエンドを反映するために必要な編集を行います。
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/storage-class-samples/storage-class-csi.yaml.templ ./storage-class-basic.yaml
[netapp-user@rhel7 trident-installer]$ vi storage-class-basic.yaml
----
. このファイルで編集する必要があるのは、 `backendType`新しく作成されたバックエンドのストレージ ドライバーの名前に値を設定します。また、後の手順で参照する必要がある名前フィールドの値にも注意してください。
+
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-csi
provisioner: csi.trident.netapp.io
parameters:
  backendType: "solidfire-san"
----
+

NOTE: オプションフィールドがあります `fsType`このファイルで定義されます。  iSCSI バックエンドでは、この値を特定の Linux ファイルシステム タイプ (XFS、ext4 など) に設定することも、削除して OpenShift が使用するファイルシステムを決定できるようにすることもできます。

. 実行 `oc`ストレージ クラスを作成するコマンド。
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ oc create -f storage-class-basic.yaml
storageclass.storage.k8s.io/basic-csi created
----
. ストレージ クラスを作成したら、最初の永続ボリューム要求 (PVC) を作成する必要があります。サンプルがあります `pvc-basic.yaml`このアクションを実行するために使用できるファイルは、sample-inputs にもあります。
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ cp sample-input/pvc-samples/pvc-basic.yaml ./
[netapp-user@rhel7 trident-installer]$ vi pvc-basic.yaml
----
. このファイルに対して行う必要がある唯一の編集は、 `storageClassName`フィールドは、先ほど作成したものと一致します。  PVC 定義は、プロビジョニングするワークロードの必要に応じてさらにカスタマイズできます。
+
[listing]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
. PVCを作成するには、 `oc`指示。作成するバックアップボリュームのサイズによっては、作成に時間がかかる場合があります。そのため、プロセスが完了するまで監視することができます。
+
[listing]
----
[netapp-user@rhel7 trident-installer]$ oc create -f pvc-basic.yaml
persistentvolumeclaim/basic created

[netapp-user@rhel7 trident-installer]$ oc get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
basic   Bound    pvc-3445b5cc-df24-453d-a1e6-b484e874349d   1Gi        RWO            basic-csi      5s
----

